development:
  adapter: postgresql
  encoding: utf-8
  database: flashcard_development
  pool: 5
  port: 5432
  username: yeaz
  password:	yeaz11235813  

test:
  adapter: postgresql
  encoding: utf-8
  database: flashcard_test
  pool: 5
  port: 5432
  username: yeaz
  password: yeaz11235813

production:
  adapter: postgresql
  encoding: utf-8
  database: flashcard_production
  pool: 5
  username: yeaz
  password: yeaz11235813
