Word.create(term: 'abate', meaning: 'lessen in intensity')
Word.create(term: 'aberrant', meaning: 'deviating')
Word.create(term: 'abjure', meaning: 'renounce or reject')
Word.create(term: 'abrogate', meaning: 'abolish')
Word.create(term: 'abscission', meaning: 'cutting off or removal')
Word.create(term: 'abscond', meaning: 'depart secretly')
Word.create(term: 'abstain', meaning: 'refrain')
Word.create(term: 'accolade', meaning: 'praise')
Word.create(term: 'accretion', meaning: 'growth, increase')
Word.create(term: 'acerbic', meaning: 'sour or bitter')
Word.create(term: 'acumen', meaning: 'keen insight')
Word.create(term: 'admonish', meaning: 'warn or express disapproval')
Word.create(term: 'adroit', meaning: 'adept, dexterous')
Word.create(term: 'adulation', meaning: 'excessive praise')
Word.create(term: 'adulterate', meaning: 'reduce purity of something')
Word.create(term: 'adumbrate', meaning: 'foreshadow')
Word.create(term: 'advocate', meaning: 'argue for or support')
Word.create(term: 'aesthetic', meaning: 'dealing with art or beauty')
Word.create(term: 'aggrandize', meaning: 'increase in power')
Word.create(term: 'alacrity', meaning: 'enthusiastic willingness')
Word.create(term: 'alchemy', meaning: 'magical transformation')
Word.create(term: 'alloy', meaning: 'make less pure')
Word.create(term: 'amalgamate', meaning: 'combine into a whole')
Word.create(term: 'ambiguity', meaning: 'uncertainty in meaning')
Word.create(term: 'ambivalence', meaning: 'feeling two opposing things')
Word.create(term: 'ameliorate', meaning: 'make better')
Word.create(term: 'amenable', meaning: 'agreeable')
Word.create(term: 'anachronism', meaning: 'something out of place historically')
Word.create(term: 'anathema', meaning: 'curse')
Word.create(term: 'anodyne', meaning: 'soothing')
Word.create(term: 'anomaly', meaning: 'abnormality')
Word.create(term: 'antagonize', meaning: 'to irritate')
Word.create(term: 'antipathy', meaning: 'aversion, dislike')
Word.create(term: 'antithetical', meaning: 'diametrically opposed')
Word.create(term: 'apathy', meaning: 'lack of interest or feeling')
Word.create(term: 'apocryphal', meaning: 'dubious authenticity or origin')
Word.create(term: 'apogee', meaning: 'farthest or highest point')
Word.create(term: 'apostate', meaning: 'one who abandons faith')
Word.create(term: 'apotheosis', meaning: 'the perfect example')
Word.create(term: 'apposite', meaning: 'relevant')
Word.create(term: 'apprise', meaning: 'give notice to')
Word.create(term: 'approbation', meaning: 'expression of praise, approval')
Word.create(term: 'appropriate', meaning: 'confiscate')
Word.create(term: 'arabesque', meaning: 'complex, ornate design')
Word.create(term: 'arcane', meaning: 'mysterious')
Word.create(term: 'archaic', meaning: 'outdated')
Word.create(term: 'arduous', meaning: 'requiring significant effort')
Word.create(term: 'arrant', meaning: 'impudent')
Word.create(term: 'arrest', meaning: 'suspend, engage')
Word.create(term: 'articulate', meaning: 'pronounce clearly')
Word.create(term: 'artless', meaning: 'natural, without artificiality')
Word.create(term: 'ascetic', meaning: 'austere')
Word.create(term: 'asperity', meaning: 'harshness')
Word.create(term: 'aspersion', meaning: 'defamation')
Word.create(term: 'assiduous', meaning: 'diligent, hard-working')
Word.create(term: 'assuage', meaning: 'ease or lessen')
Word.create(term: 'astringent', meaning: 'harsh, severe')
Word.create(term: 'attenuate', meaning: 'rarefy, lessen')
Word.create(term: 'audacious', meaning: 'daring and fearless')
Word.create(term: 'augury', meaning: 'omen')
Word.create(term: 'august', meaning: 'majestic')
Word.create(term: 'auspice', meaning: 'protection or support')
Word.create(term: 'auspicious', meaning: 'favorable')
Word.create(term: 'austere', meaning: 'bare, severely simple')
Word.create(term: 'avarice', meaning: 'greed')
Word.create(term: 'aver', meaning: 'confirm, support')
Word.create(term: 'axiom', meaning: 'universally recognized principle')
Word.create(term: 'baleful', meaning: 'sinister, pernicious')
Word.create(term: 'bane', meaning: 'cause of injury')
Word.create(term: 'beatify', meaning: 'make happy; regard as saintly')
Word.create(term: 'bedizen', meaning: 'adorn')
Word.create(term: 'belie', meaning: 'misrepresent')
Word.create(term: 'bellicose', meaning: 'belligerent, warlike')
Word.create(term: 'benign', meaning: 'favorable, harmless')
Word.create(term: 'bent', meaning: 'leaning, inclination')
Word.create(term: 'blandish', meaning: 'coax with flattery')
Word.create(term: 'blithe', meaning: 'carefree, merry')
Word.create(term: 'boisterous', meaning: 'loud, noisy')
Word.create(term: 'bolster', meaning: 'provide support or reinforcement')
Word.create(term: 'bombastic', meaning: 'pompous, grandiloquent')
Word.create(term: 'boor', meaning: 'rude or insensitive person')
Word.create(term: 'broach', meaning: 'bring up, announce')
Word.create(term: 'brook', meaning: 'tolerate, endure')
Word.create(term: 'bucolic', meaning: 'rustic and pastoral')
Word.create(term: 'burgeon', meaning: 'grow rapidly or flourish')
Word.create(term: 'burnish', meaning: 'polish')
Word.create(term: 'byzantine', meaning: 'labrynthine, complex')
Word.create(term: 'cacophony', meaning: 'discordant sound')
Word.create(term: 'cadge', meaning: 'sponge, beg')
Word.create(term: 'cajole', meaning: 'inveigle, coax')
Word.create(term: 'calumniate', meaning: 'slander, make false accusation')
Word.create(term: 'canon', meaning: 'established set of principles')
Word.create(term: 'capricious', meaning: 'inclined to change one\'s mind')
Word.create(term: 'cardinal', meaning: 'primary')
Word.create(term: 'caret', meaning: 'an insertion mark')
Word.create(term: 'carnality', meaning: 'relating to the body, flesh')
Word.create(term: 'castigation', meaning: 'severe criticism')
Word.create(term: 'catalyst', meaning: 'substance that causes change')
Word.create(term: 'causality', meaning: 'relationship of cause and effect')
Word.create(term: 'censure', meaning: 'criticize severely')
Word.create(term: 'chaos', meaning: 'confusion')
Word.create(term: 'chary', meaning: 'wary')
Word.create(term: 'chasten', meaning: 'chastise or correct')
Word.create(term: 'chauvinist', meaning: 'blindly devoted member')
Word.create(term: 'chic', meaning: 'stylish and fashionable')
Word.create(term: 'chicanery', meaning: 'trickery or subterfuge')
Word.create(term: 'chimera', meaning: 'illusion')
Word.create(term: 'choleric', meaning: 'tending toward anger')
Word.create(term: 'churlish', meaning: 'boorish')
Word.create(term: 'coalesce', meaning: 'come together')
Word.create(term: 'coda', meaning: 'concluding section')
Word.create(term: 'cogent', meaning: 'convincing')
Word.create(term: 'color', meaning: 'influence, distort')
Word.create(term: 'commensurate', meaning: 'matching, corresponding')
Word.create(term: 'complaisance', meaning: 'willingness to comply')
Word.create(term: 'confound', meaning: 'confuse')
Word.create(term: 'connoisseur', meaning: 'expert')
Word.create(term: 'consequential', meaning: 'pompous, self-important')
Word.create(term: 'contemn', meaning: 'scorn or despise')
Word.create(term: 'contentious', meaning: 'argumentative, quarrelsome')
Word.create(term: 'contiguous', meaning: 'touching, adjacent')
Word.create(term: 'contrite', meaning: 'regretful, seeking forgiveness')
Word.create(term: 'convention', meaning: 'agreed-upon principle')
Word.create(term: 'convoluted', meaning: 'complex or complicated')
Word.create(term: 'corrigible', meaning: 'capable of being set right')
Word.create(term: 'countenance', meaning: 'approve or tolerate')
Word.create(term: 'cozen', meaning: 'deceive, beguile')
Word.create(term: 'craven', meaning: 'lacking any courage')
Word.create(term: 'credulous', meaning: 'tending to believe too readily')
Word.create(term: 'crescendo', meaning: 'gradual increase')
Word.create(term: 'culpable', meaning: 'deserving blame')
Word.create(term: 'cynicism', meaning: 'belief in motivation being selfish')
Word.create(term: 'damp', meaning: 'diminish intensity')
Word.create(term: 'daunt', meaning: 'intimidate')
Word.create(term: 'dearth', meaning: 'scarcity')
Word.create(term: 'debacle', meaning: 'fiasco, complete failure')
Word.create(term: 'decorum', meaning: 'politeness or appropriateness')
Word.create(term: 'deleterious', meaning: 'injurious')
Word.create(term: 'demur', meaning: 'question or oppose')
Word.create(term: 'denigrate', meaning: 'belittle')
Word.create(term: 'denouement', meaning: 'outcome or solution')
Word.create(term: 'deprecate', meaning: 'disparage or belittle')
Word.create(term: 'depredate', meaning: 'plunder, ravage or destroy')
Word.create(term: 'derision', meaning: 'scorn, ridicule')
Word.create(term: 'derivative', meaning: 'obtained from another source')
Word.create(term: 'desiccate', meaning: 'dry out or dehydrate')
Word.create(term: 'desuetude', meaning: 'disuse')
Word.create(term: 'desultory', meaning: 'unplanned, thoughtless')
Word.create(term: 'detraction', meaning: 'verbal attack, aspersion')
Word.create(term: 'diaphanous', meaning: 'transparent, gauzy')
Word.create(term: 'diatribe', meaning: 'harsh denunciation')
Word.create(term: 'didactic', meaning: 'intended to teach or instruct')
Word.create(term: 'die', meaning: 'tool used for shaping')
Word.create(term: 'diffident', meaning: 'reserved, shy')
Word.create(term: 'digress', meaning: 'stray from the point')
Word.create(term: 'dilate', meaning: 'become wider or more open')
Word.create(term: 'dilatory', meaning: 'causing delay, procrastinating')
Word.create(term: 'dilettante', meaning: 'amateur')
Word.create(term: 'din', meaning: 'sustained noise')
Word.create(term: 'dirge', meaning: 'mournful song for the dead')
Word.create(term: 'disabuse', meaning: 'set right')
Word.create(term: 'discomfit', meaning: 'defeat, put down')
Word.create(term: 'discordant', meaning: 'conflicting')
Word.create(term: 'discretion', meaning: 'cautious reserve in speech')
Word.create(term: 'disinterested', meaning: 'unbiased')
Word.create(term: 'disparage', meaning: 'belittle')
Word.create(term: 'disparate', meaning: 'fundamentally distinct')
Word.create(term: 'dissemble', meaning: 'mislead')
Word.create(term: 'dissolution', meaning: 'disintegration')
Word.create(term: 'dissonance', meaning: 'lack of harmony')
Word.create(term: 'distrait', meaning: 'distracted, absent-minded')
Word.create(term: 'divulge', meaning: 'disclose something secret')
Word.create(term: 'doggerel', meaning: 'trivial poetry')
Word.create(term: 'dogmatic', meaning: 'stubbornly opinionated')
Word.create(term: 'dross', meaning: 'waste or foreign matter')
Word.create(term: 'dulcet', meaning: 'melodious, harmonious')
Word.create(term: 'dupe', meaning: 'one who is deceived')
Word.create(term: 'dynamo', meaning: 'generator')
Word.create(term: 'ebullience', meaning: 'enthusiastic expression')
Word.create(term: 'eccentric', meaning: 'departing from norms')
Word.create(term: 'eclectic', meaning: 'from various sources')
Word.create(term: 'edifying', meaning: 'enlightening, informative')
Word.create(term: 'efficacy', meaning: 'effectiveness')
Word.create(term: 'effrontery', meaning: 'extreme boldness')
Word.create(term: 'effusive', meaning: 'excessively demonstrative')
Word.create(term: 'egress', meaning: 'exit')
Word.create(term: 'elegy', meaning: 'mournful poem')
Word.create(term: 'eloquent', meaning: 'well-spoken, expressive')
Word.create(term: 'emollient', meaning: 'soothing')
Word.create(term: 'empirical', meaning: 'based on observation')
Word.create(term: 'encomium', meaning: 'glowing and enthusiastic praise')
Word.create(term: 'endemic', meaning: 'found in a particular location')
Word.create(term: 'enervate', meaning: 'to weaken')
Word.create(term: 'engender', meaning: 'cause, produce, give rise to')
Word.create(term: 'enigmatic', meaning: 'mysterious, obscure')
Word.create(term: 'ennui', meaning: 'dissatisfaction')
Word.create(term: 'enormity', meaning: 'evilness')
Word.create(term: 'ephemeral', meaning: 'brief, fleeting')
Word.create(term: 'epicure', meaning: 'one devoted to sensual pleasure')
Word.create(term: 'episodic', meaning: 'occurring at intervals')
Word.create(term: 'epithet', meaning: 'disparagin word or phrase')
Word.create(term: 'epitome', meaning: 'embodiment, quintessence')
Word.create(term: 'equanimity', meaning: 'composure, self-possession')
Word.create(term: 'equable', meaning: 'not able to be easily disturbed')
Word.create(term: 'equivocate', meaning: 'use ambiguous language to deceive')
Word.create(term: 'errant', meaning: 'traveling')
Word.create(term: 'erratic', meaning: 'without consistency')
Word.create(term: 'erudite', meaning: 'very learned, scholarly')
Word.create(term: 'eschew', meaning: 'to shun or avoid')
Word.create(term: 'esoteric', meaning: 'understood by only a small group')
Word.create(term: 'essay', meaning: 'to test or try')
Word.create(term: 'estimable', meaning: 'worthy, formidable')
Word.create(term: 'eulogy', meaning: 'speech honoring the dead')
Word.create(term: 'evanescent', meaning: 'tending to disappear like vapor')
Word.create(term: 'evince', meaning: 'show clearly, indicate')
Word.create(term: 'exacerbate', meaning: 'make worse or more severe')
Word.create(term: 'exact', meaning: 'demand, require')
Word.create(term: 'excoriate', meaning: 'censure scathingly')
Word.create(term: 'exculpate', meaning: 'exonerate, clear of blame')
Word.create(term: 'exemplar', meaning: 'model')
Word.create(term: 'exhort', meaning: 'incite, make urgent appeals')
Word.create(term: 'exigent', meaning: 'urgent, pressing')
Word.create(term: 'exonerate', meaning: 'remove blame')
Word.create(term: 'expatiate', meaning: 'discuss at length')
Word.create(term: 'expiate', meaning: 'atone or make amends for')
Word.create(term: 'expurgate', meaning: 'remove obscenity, purify')
Word.create(term: 'extant', meaning: 'existing, not destroyed or lost')
Word.create(term: 'extemporaneous', meaning: 'improvised, done without preparation')
Word.create(term: 'extirpate', meaning: 'destroy')
Word.create(term: 'facetious', meaning: 'playful, humorous')
Word.create(term: 'fallacy', meaning: 'invalid, incorrect notion')
Word.create(term: 'fallow', meaning: 'untilled, inactive, dormant')
Word.create(term: 'fanatical', meaning: 'zealous')
Word.create(term: 'fatuous', meaning: 'silly, inanely foolish')
Word.create(term: 'fawn', meaning: 'flatter, praise excessively')
Word.create(term: 'feckless', meaning: 'ineffectual, irresponsible')
Word.create(term: 'felicitous', meaning: 'suitably expressed')
Word.create(term: 'fell', meaning: 'barren or stony hill')
Word.create(term: 'fervent', meaning: 'greatly emotional or zealous')
Word.create(term: 'fetid', meaning: 'stinking')
Word.create(term: 'fetter', meaning: 'put in chains, restrain')
Word.create(term: 'filibuster', meaning: 'intentional obstruction')
Word.create(term: 'filigree', meaning: 'ornamental work')
Word.create(term: 'flag', meaning: 'sag or droop, decline')
Word.create(term: 'flip', meaning: 'sarcastic, impertinent')
Word.create(term: 'florid', meaning: 'flushed with color')
Word.create(term: 'flout', meaning: 'demonstrate contempt for')
Word.create(term: 'foment', meaning: 'stir up, incite')
Word.create(term: 'forbearance', meaning: 'patience, willingness to wait')
Word.create(term: 'ford', meaning: 'wade across a river')
Word.create(term: 'forestall', meaning: 'avert an action')
Word.create(term: 'forswear', meaning: 'renounce')
Word.create(term: 'fortuitous', meaning: 'happening by chance')
Word.create(term: 'fracas', meaning: 'noisy fight or quarrel')
Word.create(term: 'fractious', meaning: 'quarrelsome, rebellious')
Word.create(term: 'froward', meaning: 'stubbornly disobedient')
Word.create(term: 'fulminate', meaning: 'attack loudly or denounce')
Word.create(term: 'furtive', meaning: 'stealthy')
Word.create(term: 'gainsay', meaning: 'deny, contradict')
Word.create(term: 'gambol', meaning: 'skip about playfully')
Word.create(term: 'garner', meaning: 'gather and save')
Word.create(term: 'garrulous', meaning: 'pointlessly talkative')
Word.create(term: 'gauche', meaning: 'crude, awkward')
Word.create(term: 'germane', meaning: 'relevant to the subject matter')
Word.create(term: 'glib', meaning: 'lacking depth, superficial')
Word.create(term: 'gossamer', meaning: 'delicate, insubstantial')
Word.create(term: 'grandiloquence', meaning: 'pompous speech or expression')
Word.create(term: 'gregarious', meaning: 'sociable, outgoing')
Word.create(term: 'grouse', meaning: 'complain or grumble')
Word.create(term: 'guile', meaning: 'trickery, duplicity')
Word.create(term: 'guy', meaning: 'rope used to guide')
Word.create(term: 'hackneyed', meaning: 'trite from overuse')
Word.create(term: 'halcyon', meaning: 'calm and peaceful')
Word.create(term: 'hallow', meaning: 'set apart as holy')
Word.create(term: 'harangue', meaning: 'deliver a loud, pompous speech')
Word.create(term: 'harrow', meaning: 'distress, create stress')
Word.create(term: 'hedonism', meaning: 'devotion to pleasurable pursuits')
Word.create(term: 'hegemony', meaning: 'consistent dominance or influence')
Word.create(term: 'heretical', meaning: 'violating accepted convention')
Word.create(term: 'hermetic', meaning: 'impervious to outside influence')
Word.create(term: 'heterodox', meaning: 'unorthodox, heretical')
Word.create(term: 'hirsute', meaning: 'hairy, shaggy')
Word.create(term: 'homily', meaning: 'sermon, morally instructive lecture')
Word.create(term: 'homogenous', meaning: 'same throughout')
Word.create(term: 'hubris', meaning: 'arrogant presumption or pride')
Word.create(term: 'hyperbole', meaning: 'exaggerated statement')
Word.create(term: 'iconoclast', meaning: 'one who attacks conventions')
Word.create(term: 'idolatrous', meaning: 'excessively devoted')
Word.create(term: 'idyll', meaning: 'carefree episode')
Word.create(term: 'ignominious', meaning: 'shameful, dishonorable')
Word.create(term: 'imbroglio', meaning: 'difficult or embrassing situation')
Word.create(term: 'imminent', meaning: 'about to happen')
Word.create(term: 'immutable', meaning: 'not capable of change')
Word.create(term: 'impassive', meaning: 'showing no emotion')
Word.create(term: 'impecunious', meaning: 'without money')
Word.create(term: 'imperious', meaning: 'commanding, masterful')
Word.create(term: 'imperturbable', meaning: 'extremely calm')
Word.create(term: 'impetuous', meaning: 'impulsive')
Word.create(term: 'implacable', meaning: 'incapable of being appeased')
Word.create(term: 'importune', meaning: 'ask incessantly, beg')
Word.create(term: 'impudent', meaning: 'shamelessly bold')
Word.create(term: 'impugn', meaning: 'attack or assail verbally')
Word.create(term: 'impunity', meaning: 'immunity from punishment')
Word.create(term: 'impute', meaning: 'ascribe')
Word.create(term: 'inalienable', meaning: 'cannot be transferred')
Word.create(term: 'inchoate', meaning: 'in an initial stage')
Word.create(term: 'incipient', meaning: 'become apparent')
Word.create(term: 'indefatigable', meaning: 'not easily exhaustible')
Word.create(term: 'indifferent', meaning: 'apathetic')
Word.create(term: 'indolent', meaning: 'lazy, listless')
Word.create(term: 'ineluctable', meaning: 'certain, inevitable')
Word.create(term: 'inert', meaning: 'unmoving, sluggish')
Word.create(term: 'ingenuous', meaning: 'artless, frank')
Word.create(term: 'inherent', meaning: 'intrinsic')
Word.create(term: 'inimical', meaning: 'damaging, harmful')
Word.create(term: 'inimitable', meaning: 'one of a kind')
Word.create(term: 'iniquity', meaning: 'wickedness')
Word.create(term: 'innervate', meaning: 'supply with nerves, energize')
Word.create(term: 'innocuous', meaning: 'harmless, causing no damage')
Word.create(term: 'inscrutable', meaning: 'incapable of being understood')
Word.create(term: 'insensible', meaning: 'unconscious')
Word.create(term: 'insipid', meaning: 'without taste or flavor')
Word.create(term: 'insouciant', meaning: 'unconcerned, carefree')
Word.create(term: 'insular', meaning: 'parochial, narrow-minded')
Word.create(term: 'interdict', meaning: 'prohibit, forbid')
Word.create(term: 'intimate', meaning: 'imply, suggest')
Word.create(term: 'intractable', meaning: 'not easily managed, stubborn')
Word.create(term: 'intransigent', meaning: 'resuing to compromise')
Word.create(term: 'intrepid', meaning: 'steadfast, courageous')
Word.create(term: 'inundate', meaning: 'cover or overwhelm')
Word.create(term: 'inured', meaning: 'accustomed to')
Word.create(term: 'inveigh', meaning: 'attack verbally')
Word.create(term: 'inveigle', meaning: 'obtain by deception')
Word.create(term: 'inveterate', meaning: 'deep rooted, habitual')
Word.create(term: 'invidious', meaning: 'arousing envy')
Word.create(term: 'irascible', meaning: 'easily angered')
Word.create(term: 'itinerate', meaning: 'travel from place to place')
Word.create(term: 'jejune', meaning: 'uninteresting; childish')
Word.create(term: 'jibe', meaning: 'agree')
Word.create(term: 'jocose', meaning: 'humorous')
Word.create(term: 'kinetic', meaning: 'lively, active')
Word.create(term: 'labile', meaning: 'readily open to change, unstable')
Word.create(term: 'lachrymose', meaning: 'causing tears')
Word.create(term: 'laconic', meaning: 'using few words')
Word.create(term: 'lassitude', meaning: 'weariness')
Word.create(term: 'laud', meaning: 'praise highly')
Word.create(term: 'lavish', meaning: 'extravagant')
Word.create(term: 'lethargic', meaning: 'sluggish')
Word.create(term: 'libertine', meaning: 'unrestrained by morality')
Word.create(term: 'limn', meaning: 'draw, outline in detail')
Word.create(term: 'limpid', meaning: 'transparent, serene')
Word.create(term: 'list', meaning: 'tilt or lean to one side')
Word.create(term: 'loquacious', meaning: 'extremely talkative')
Word.create(term: 'lucid', meaning: 'intelligible, sound')
Word.create(term: 'lumber', meaning: 'move heavily and clumsily')
Word.create(term: 'luminous', meaning: 'enlightened, clear')
Word.create(term: 'magnanimity', meaning: 'quality of being generously noble')
Word.create(term: 'malevolent', meaning: 'showing vicious ill will')
Word.create(term: 'malinger', meaning: 'feign illness to avoid work')
Word.create(term: 'malleable', meaning: 'capable of being shaped')
Word.create(term: 'martial', meaning: 'associated with war')
Word.create(term: 'martinet', meaning: 'rigid disciplinarian')
Word.create(term: 'maunder', meaning: 'talk or move aimlessly')
Word.create(term: 'maverick', meaning: 'independent individual')
Word.create(term: 'melancholy', meaning: 'tending toward sadness')
Word.create(term: 'mellifluous', meaning: 'sweetly flowing')
Word.create(term: 'mendacity', meaning: 'dishonesty')
Word.create(term: 'mendicant', meaning: 'beggar')
Word.create(term: 'mercurial', meaning: 'unpredictable')
Word.create(term: 'meretricious', meaning: 'pretentious, attractive but false')
Word.create(term: 'meticulous', meaning: 'extremely precise')
Word.create(term: 'mettlesome', meaning: 'courageous')
Word.create(term: 'militate', meaning: 'have weight or bearing on')
Word.create(term: 'milk', meaning: 'exploit, squeeze every last ounce')
Word.create(term: 'minatory', meaning: 'menacing, threatening')
Word.create(term: 'mince', meaning: 'speak too carefully, tiptoe')
Word.create(term: 'misanthrope', meaning: 'one who hates mankind')
Word.create(term: 'misogynist', meaning: 'one who hates women')
Word.create(term: 'mitigate', meaning: 'make less intense')
Word.create(term: 'mollify', meaning: 'calm or soothe')
Word.create(term: 'monotony', meaning: 'lack of variety or change')
Word.create(term: 'morose', meaning: 'sad, sullen, melancholy')
Word.create(term: 'multifaceted', meaning: 'having many aspects')
Word.create(term: 'multifarious', meaning: 'varied, greatly diversified')
Word.create(term: 'mundane', meaning: 'typical, of the ordinary')
Word.create(term: 'nadir', meaning: 'low point, perigee')
Word.create(term: 'nascent', meaning: 'coming into being')
Word.create(term: 'natty', meaning: 'trimly neat and tidy')
Word.create(term: 'nebulous', meaning: 'vague, lacking clear form')
Word.create(term: 'neologism', meaning: 'new word, expression')
Word.create(term: 'neophyte', meaning: 'recent convert, beginner')
Word.create(term: 'nexus', meaning: 'connection; center or focus')
Word.create(term: 'nice', meaning: 'exacting, extremely precise')
Word.create(term: 'noisome', meaning: 'offensive to the sense of smell')
Word.create(term: 'nonplussed', meaning: 'baffled')
Word.create(term: 'nostrum', meaning: 'cure-all, questionable remedy')
Word.create(term: 'noxious', meaning: 'harmful, injurious')
Word.create(term: 'obdurate', meaning: 'unyielding, hardhearted')
Word.create(term: 'obeisance', meaning: 'gesture that expresses deference')
Word.create(term: 'obfuscate', meaning: 'deliberately obscure')
Word.create(term: 'obsequious', meaning: 'exhibiting a fawning attentiveness')
Word.create(term: 'obstinate', meaning: 'stubborn')
Word.create(term: 'obstreperous', meaning: 'noisy, boisterous')
Word.create(term: 'obtain', meaning: 'be established, prevail')
Word.create(term: 'obtuse', meaning: 'lacking sharpness of intellect')
Word.create(term: 'obviate', meaning: 'make unnecessary')
Word.create(term: 'occlude', meaning: 'obstruct or block')
Word.create(term: 'occult', meaning: 'hidden, concealed')
Word.create(term: 'odious', meaning: 'hateful')
Word.create(term: 'officious', meaning: 'pushy in offering unwanted service')
Word.create(term: 'onerous', meaning: 'troubling, burdensome')
Word.create(term: 'opaque', meaning: 'impermeable by light')
Word.create(term: 'opprobrium', meaning: 'disgrace, contempt')
Word.create(term: 'oscillation', meaning: 'act of swinging back and forth')
Word.create(term: 'ossified', meaning: 'unreceptive to change')
Word.create(term: 'ostensible', meaning: 'seeming, professed')
Word.create(term: 'ostentatious', meaning: 'pretentious')
Word.create(term: 'overweening', meaning: 'presumptuously arrogant')
Word.create(term: 'paean', meaning: 'expression of praise')
Word.create(term: 'palliate', meaning: 'mitigate')
Word.create(term: 'pandemic', meaning: 'widespread')
Word.create(term: 'panegyric', meaning: 'formal expression of praise')
Word.create(term: 'paradigm', meaning: 'model; framework')
Word.create(term: 'paradox', meaning: 'contradiction')
Word.create(term: 'paragon', meaning: 'perfect example')
Word.create(term: 'pariah', meaning: 'outcast')
Word.create(term: 'parody', meaning: 'humorous imitation')
Word.create(term: 'parry', meaning: 'block, evade or ward off')
Word.create(term: 'parsimonious', meaning: 'cheap, miserly')
Word.create(term: 'partisan', meaning: 'one-sided, biased')
Word.create(term: 'paucity', meaning: 'scarcity')
Word.create(term: 'peccadillo', meaning: 'slight offense')
Word.create(term: 'pedagogy', meaning: 'art of profession of training')
Word.create(term: 'pedantic', meaning: 'ostentatious display of learning')
Word.create(term: 'pedestrian', meaning: 'commonplace')
Word.create(term: 'penchant', meaning: 'strong inclination')
Word.create(term: 'penurious', meaning: 'excessively thrifty, ungenerous')
Word.create(term: 'peremptory', meaning: 'imperious')
Word.create(term: 'perennial', meaning: 'happening repeatedly')
Word.create(term: 'perfidy', meaning: 'intentional breach of faith')
Word.create(term: 'perfunctory', meaning: 'done without care or interest')
Word.create(term: 'peripatetic', meaning: 'itinerant, traveling')
Word.create(term: 'pernicious', meaning: 'extremely harmful')
Word.create(term: 'personable', meaning: 'pleasing in appearance')
Word.create(term: 'perspicacious', meaning: 'acutely perceptive')
Word.create(term: 'peruse', meaning: 'examine with great care')
Word.create(term: 'pervade', meaning: 'permeate throughout')
Word.create(term: 'petrous', meaning: 'like a rock, hard, stony')
Word.create(term: 'petulant', meaning: 'impatient, irritable')
Word.create(term: 'philanthropic', meaning: 'humanitarian')
Word.create(term: 'philistine', meaning: 'crass individual')
Word.create(term: 'phlegmatic', meaning: 'calm, unemotional')
Word.create(term: 'picaresque', meaning: 'involving adventurers')
Word.create(term: 'pied', meaning: 'multi-colored, usually in blotches')
Word.create(term: 'pillory', meaning: 'punish, hold up to public scorn')
Word.create(term: 'pine', meaning: 'yearn intensely')
Word.create(term: 'pious', meaning: 'extremely reverent or devout')
Word.create(term: 'piquant', meaning: 'stimulating')
Word.create(term: 'pique', meaning: 'resentment')
Word.create(term: 'pirate', meaning: 'use or reproduce illegally')
Word.create(term: 'pith', meaning: 'essential or central part')
Word.create(term: 'placate', meaning: 'appease, calm')
Word.create(term: 'plaintive', meaning: 'mournful, melancholy')
Word.create(term: 'plangent', meaning: 'pounding, thundering')
Word.create(term: 'plastic', meaning: 'moldable')
Word.create(term: 'platitude', meaning: 'a superficial or trite remark')
Word.create(term: 'plethora', meaning: 'overabundance')
Word.create(term: 'pluck', meaning: 'courage')
Word.create(term: 'plumb', meaning: 'measure the depth, examine')
Word.create(term: 'plummet', meaning: 'drop straight down')
Word.create(term: 'poignant', meaning: 'touching, emotional')
Word.create(term: 'polemical', meaning: 'controversial')
Word.create(term: 'pragmatic', meaning: 'practical')
Word.create(term: 'prate', meaning: 'chatter')
Word.create(term: 'prattle', meaning: 'babble meaninglessly')
Word.create(term: 'precarious', meaning: 'uncertain, risky')
Word.create(term: 'precept', meaning: 'rule of conduct')
Word.create(term: 'precipitate', meaning: 'acting with excessive haste')
Word.create(term: 'precursor', meaning: 'predecessor')
Word.create(term: 'predilection', meaning: 'preference')
Word.create(term: 'preempt', meaning: 'replace, supersede')
Word.create(term: 'preen', meaning: 'dress up')
Word.create(term: 'prescience', meaning: 'foreknowledge')
Word.create(term: 'presumptuous', meaning: 'overstepping bounds')
Word.create(term: 'prevaricate', meaning: 'deliberately avoid the truth')
Word.create(term: 'pristine', meaning: 'pure, uncorrupted')
Word.create(term: 'prize', meaning: 'pry')
Word.create(term: 'probity', meaning: 'uprightness')
Word.create(term: 'proclivity', meaning: 'natural inclination')
Word.create(term: 'prodigal', meaning: 'recklessly wasteful')
Word.create(term: 'prodigious', meaning: 'abundant in size')
Word.create(term: 'profligate', meaning: 'exceesively wasteful')
Word.create(term: 'profuse', meaning: 'extravagant')
Word.create(term: 'prolific', meaning: 'producing large volumes')
Word.create(term: 'prolix', meaning: 'long-winded, verbose')
Word.create(term: 'propensity', meaning: 'natural inclination')
Word.create(term: 'propinquity', meaning: 'nearness in time or place')
Word.create(term: 'propitiate', meaning: 'appease or pacify')
Word.create(term: 'propitious', meaning: 'auspicious, favorable')
Word.create(term: 'propriety', meaning: 'appropriateness')
Word.create(term: 'prosaic', meaning: 'dull, unimaginative')
Word.create(term: 'proscribe', meaning: 'outlaw or prohibit')
Word.create(term: 'provident', meaning: 'frugal, looking to the future')
Word.create(term: 'puerile', meaning: 'childish, immature')
Word.create(term: 'pugnacious', meaning: 'contentious, quarrelsome')
Word.create(term: 'punctilious', meaning: 'precise, paying attention')
Word.create(term: 'pundit', meaning: 'authority on a subject')
Word.create(term: 'pungent', meaning: 'having a strong smell, penetrating')
Word.create(term: 'pusillanimous', meaning: 'cowardly, craven')
Word.create(term: 'putrefy', meaning: 'rot, decay')
Word.create(term: 'quaff', meaning: 'drink deeply')
Word.create(term: 'quail', meaning: 'shrink back in fear')
Word.create(term: 'qualify', meaning: 'limit')
Word.create(term: 'qualms', meaning: 'reservations, causes for hesitancy')
Word.create(term: 'queries', meaning: 'questions, inquiries')
Word.create(term: 'querulous', meaning: 'prone to complaining or grumbling')
Word.create(term: 'quiescence', meaning: 'stillness')
Word.create(term: 'quotidian', meaning: 'commonplace')
Word.create(term: 'rail', meaning: 'to complain about bitterly')
Word.create(term: 'ramify', meaning: 'be divided, branch out')
Word.create(term: 'rancorous', meaning: 'bitterly resentful')
Word.create(term: 'rapacious', meaning: 'voracious, greedy')
Word.create(term: 'rarefy', meaning: 'make thin, less dense')
Word.create(term: 'rebus', meaning: 'riddle')
Word.create(term: 'recalcitrant', meaning: 'defiant of authority')
Word.create(term: 'recant', meaning: 'retract a previously held belief')
Word.create(term: 'recapitulate', meaning: 'summarize')
Word.create(term: 'recondite', meaning: 'hidden, concealed')
Word.create(term: 'reconnoiter', meaning: 'make a preliminary inspection')
Word.create(term: 'recumbent', meaning: 'leaning, resting, prone')
Word.create(term: 'redolent', meaning: 'fragrant')
Word.create(term: 'redoubtable', meaning: 'awe-inspiring, worthy of honor')
Word.create(term: 'refulgent', meaning: 'radiant, shiny, brilliant')
Word.create(term: 'refute', meaning: 'disprove, successfully argue against')
Word.create(term: 'regale', meaning: 'delight or entertain')
Word.create(term: 'relegate', meaning: 'forcibly assign')
Word.create(term: 'remonstrate', meaning: 'to protest')
Word.create(term: 'renege', meaning: 'go back on a promise')
Word.create(term: 'rent', meaning: 'torn, split apart')
Word.create(term: 'repine', meaning: 'long for')
Word.create(term: 'repudiate', meaning: 'disown')
Word.create(term: 'rescind', meaning: 'invalidate, repeal')
Word.create(term: 'resolute', meaning: 'adamant, determined')
Word.create(term: 'reticent', meaning: 'quiet, reserved')
Word.create(term: 'reverent', meaning: 'feeling awe and respect')
Word.create(term: 'rhetoric', meaning: 'art of using language')
Word.create(term: 'risible', meaning: 'hilarious, provoking laughter')
Word.create(term: 'rubric', meaning: 'authoritative rule')
Word.create(term: 'rue', meaning: 'regret, feel remorse')
Word.create(term: 'sagacious', meaning: 'having sound judgement')
Word.create(term: 'salacious', meaning: 'causing sexual desire')
Word.create(term: 'salient', meaning: 'prominent, highly relevant')
Word.create(term: 'salubrious', meaning: 'promoting health or well-being')
Word.create(term: 'salutary', meaning: 'remedial, wholesome')
Word.create(term: 'sanctimony', meaning: 'self-righteousness')
Word.create(term: 'sanction', meaning: 'authoritative permission')
Word.create(term: 'sanguine', meaning: 'cheerful, confident')
Word.create(term: 'sap', meaning: 'enervate, weaken')
Word.create(term: 'satiate', meaning: 'satisfy to excess')
Word.create(term: 'satire', meaning: 'work ridiculing human vice')
Word.create(term: 'saturnine', meaning: 'gloomy, morose')
Word.create(term: 'scurvy', meaning: 'contemptible, despicable')
Word.create(term: 'sedulous', meaning: 'diligent, persistent')
Word.create(term: 'seine', meaning: 'large net to catch fish')
Word.create(term: 'sere', meaning: 'withered, arid')
Word.create(term: 'seminal', meaning: 'like a seed')
Word.create(term: 'shard', meaning: 'piece of broken pottery')
Word.create(term: 'simper', meaning: 'smirk')
Word.create(term: 'sinecure', meaning: 'position requiring little work')
Word.create(term: 'singular', meaning: 'exceptional, unusual')
Word.create(term: 'sinuous', meaning: 'winding, curving')
Word.create(term: 'slake', meaning: 'satisfy, lessen intensity')
Word.create(term: 'sodden', meaning: 'soaked or drenched')
Word.create(term: 'solder', meaning: 'weld, fuse or join')
Word.create(term: 'solicitous', meaning: 'concerned and attentive, eager')
Word.create(term: 'solvent', meaning: 'able to meet financial obligations')
Word.create(term: 'sophistry', meaning: 'fallacious reasoning')
Word.create(term: 'sophomoric', meaning: 'exhibiting immaturity')
Word.create(term: 'soporific', meaning: 'causing drowsiness')
Word.create(term: 'sordid', meaning: 'filthy')
Word.create(term: 'sparse', meaning: 'thin, not dense')
Word.create(term: 'specious', meaning: 'seeming true but actually false')
Word.create(term: 'spendthrift', meaning: 'one who spends money wastefully')
Word.create(term: 'splenetic', meaning: 'bad-tempered, irritable')
Word.create(term: 'sporadic', meaning: 'occurring only occasionally')
Word.create(term: 'spurious', meaning: 'lacking authenticity')
Word.create(term: 'squalid', meaning: 'sordid')
Word.create(term: 'squander', meaning: 'waste by spending irresponsibly')
Word.create(term: 'stanch', meaning: 'stop the flow of a fluid')
Word.create(term: 'static', meaning: 'not moving')
Word.create(term: 'steep', meaning: 'saturate or completely soak')
Word.create(term: 'stentorian', meaning: 'extremely loud and powerful')
Word.create(term: 'stint', meaning: 'restrain, sparing or frugal')
Word.create(term: 'stoic', meaning: 'unaffected by pleasure or pain')
Word.create(term: 'stolid', meaning: 'calm, impassive')
Word.create(term: 'striated', meaning: 'striped, grooved, or banded')
Word.create(term: 'strut', meaning: 'structural support')
Word.create(term: 'stupefy', meaning: 'to stun, baffle')
Word.create(term: 'stymie', meaning: 'to block, thwart')
Word.create(term: 'subpoena', meaning: 'court order requiring appearance')
Word.create(term: 'subtle', meaning: 'not obvious, elusive')
Word.create(term: 'succinct', meaning: 'brief, concise')
Word.create(term: 'succor', meaning: 'assistance, relief in time')
Word.create(term: 'sundry', meaning: 'various, miscellaneous')
Word.create(term: 'supercilious', meaning: 'disdainful, arrogant')
Word.create(term: 'superfluous', meaning: 'exceeding what is necessary')
Word.create(term: 'supine', meaning: 'inactive, apathetic')
Word.create(term: 'supplant', meaning: 'take the place of')
Word.create(term: 'suppliant', meaning: 'asking humbly')
Word.create(term: 'supplicant', meaning: 'beggar')
Word.create(term: 'surfeit', meaning: 'feed or supply in excess')
Word.create(term: 'sycophant', meaning: 'flatterer')
Word.create(term: 'synthesis', meaning: 'the combination of parts')
Word.create(term: 'table', meaning: 'remove from consideration')
Word.create(term: 'taciturn', meaning: 'not talkative')
Word.create(term: 'talisman', meaning: 'good-luck charm')
Word.create(term: 'tamp', meaning: 'plug, drive in or down')
Word.create(term: 'tautology', meaning: 'repetition, redundancy')
Word.create(term: 'tawdry', meaning: 'cheap, gaudy, showy')
Word.create(term: 'tenacity', meaning: 'adherence to something valued')
Word.create(term: 'tendentious', meaning: 'biased')
Word.create(term: 'tender', meaning: 'offer formally')
Word.create(term: 'tenuous', meaning: 'having little substance or strength')
Word.create(term: 'terse', meaning: 'brief and concise in wording')
Word.create(term: 'timorous', meaning: 'timid, fearful, diffident')
Word.create(term: 'tirade', meaning: 'long and critical speech')
Word.create(term: 'toady', meaning: 'sycophant, yes-man')
Word.create(term: 'torpid', meaning: 'lethargic, sluggish')
Word.create(term: 'torque', meaning: 'force that causes rotation')
Word.create(term: 'torrid', meaning: 'scorching, ardent')
Word.create(term: 'tortuous', meaning: 'winding, twisting')
Word.create(term: 'tout', meaning: 'publicly praise')
Word.create(term: 'tractable', meaning: 'docile, obedient')
Word.create(term: 'transient', meaning: 'fleeting, brief')
Word.create(term: 'travesty', meaning: 'mockery, caricature')
Word.create(term: 'trenchant', meaning: 'sharply perceptive, keen')
Word.create(term: 'truculent', meaning: 'fierce, eager to fight')
Word.create(term: 'tumid', meaning: 'swollen')
Word.create(term: 'turbid', meaning: 'muddy, clouded')
Word.create(term: 'turgid', meaning: 'swollen, excessively ornate')
Word.create(term: 'turpitude', meaning: 'depravity, baseness')
Word.create(term: 'tyro', meaning: 'novice, beginner in learning')
Word.create(term: 'ubiquitous', meaning: 'existing everywhere')
Word.create(term: 'umbrage', meaning: 'offense, resentment')
Word.create(term: 'undulate', meaning: 'fluctuate')
Word.create(term: 'unfeigned', meaning: 'genuine')
Word.create(term: 'untenable', meaning: 'indefensible')
Word.create(term: 'untoward', meaning: 'troublesome, adverse')
Word.create(term: 'upbraid', meaning: 'scold, chastise')
Word.create(term: 'urbane', meaning: 'sophisticated, refined')
Word.create(term: 'usury', meaning: 'charging exorbitant interest')
Word.create(term: 'vacillate', meaning: 'waver indecisively')
Word.create(term: 'variegated', meaning: 'multicolored')
Word.create(term: 'vaunt', meaning: 'brag or boast')
Word.create(term: 'venal', meaning: 'capable of being bought or bribed')
Word.create(term: 'venerate', meaning: 'revere')
Word.create(term: 'veracity', meaning: 'truthfulness, honesty')
Word.create(term: 'verisimilitude', meaning: 'appearing true or real')
Word.create(term: 'veritable', meaning: 'authentic, real')
Word.create(term: 'vexation', meaning: 'annoyance, irritation')
Word.create(term: 'vigilant', meaning: 'alertly watchful')
Word.create(term: 'vilify', meaning: 'defame')
Word.create(term: 'virulent', meaning: 'extremely harmful or poisonous')
Word.create(term: 'viscous', meaning: 'thick')
Word.create(term: 'vitiate', meaning: 'reduce the value of')
Word.create(term: 'vituperate', meaning: 'use harsh condemnatory language')
Word.create(term: 'volatile', meaning: 'readily changing to a vapor')
Word.create(term: 'voracious', meaning: 'having an insatiable appetite')
Word.create(term: 'waft', meaning: 'light breeze, puff')
Word.create(term: 'waver', meaning: 'move to and fro')
Word.create(term: 'welter', meaning: 'writhe, toss about')
Word.create(term: 'wend', meaning: 'proceed, walk')
Word.create(term: 'whet', meaning: 'sharpen, stimulate')
Word.create(term: 'whimsical', meaning: 'imaginative')
Word.create(term: 'zealous', meaning: 'fervent, ardent impassioned')
